// app/components/playerSection.tsx
import React from "react";
import type { EarnPointArgs } from "./winButton";
import WinButton from "./winButton";

interface PlayerSectionProps {
  playerName: string;
  playerIndex: number;
  playerScore: number;
  isDisabled: boolean;
  winFunction: (args: EarnPointArgs) => void;
}

export default function PlayerSection({
  playerName,
  playerIndex,
  playerScore,
  isDisabled,
  winFunction,
}: PlayerSectionProps) {
  const buttons: { winName: string; points: number; reasonSuffix: string }[] = [
    { winName: "Spin", points: 1, reasonSuffix: "Spin Finish" },
    { winName: "Over", points: 2, reasonSuffix: "Over Finish" },
    { winName: "Burst", points: 2, reasonSuffix: "Burst Finish" },
    { winName: "Xtreme", points: 3, reasonSuffix: "Xtreme Finish" },
    {
      winName: "Launch Error",
      points: 1,
      reasonSuffix: "Opponent Launch Error",
    },
  ];

  return (
    <div className="col text-center">
      <h3>{playerName}</h3>
      <h4>{playerScore}</h4>
      <div className="btn-group">
        {buttons.map(({ winName, points, reasonSuffix }) => (
          <WinButton
            key={winName}
            winName={winName}
            isDisabled={isDisabled}
            clickFunc={winFunction}
            args={{
              Points: points,
              Player: playerIndex,
              Reason: `${playerName} ${reasonSuffix}`,
            }}
          />
        ))}
      </div>
    </div>
  );
}

// app/components/PlayerSection.vue
<script setup lang="ts">
import type { EarnPointArgs } from "../types/earnPointArgs";

defineProps<{
  playerName: string;
  playerIndex: number;
  playerScore: number;
  isDisabled: boolean;
  winFunction: (args: EarnPointArgs) => void;
}>();
</script>

<template>
  <div class="flex flex-col justify-center items-center">
    <h3>{{ playerName }}</h3>
    <div class="flex flex-row">
      <h4 v-if="playerIndex === 1" class="text-7xl grow m-24">
        {{ playerScore }}
      </h4>
      <div
        :class="`flex flex-col max-w-24 ${playerIndex ? 'justify-items-end' : 'justify-items-start'}`"
      >
        <WinButton
          win-name="Spin"
          :is-disabled="isDisabled"
          @clicked="
            winFunction({
              Points: 1,
              Player: playerIndex,
              Reason: `${playerName} Spin Finish`,
            })
          "
        />
        <WinButton
          win-name="Over"
          :is-disabled="isDisabled"
          @clicked="
            winFunction({
              Points: 2,
              Player: playerIndex,
              Reason: `${playerName} Over Finish`,
            })
          "
        />
        <WinButton
          win-name="Burst"
          :is-disabled="isDisabled"
          @clicked="
            winFunction({
              Points: 2,
              Player: playerIndex,
              Reason: `${playerName} Burst Finish`,
            })
          "
        />
        <WinButton
          win-name="Xtreme"
          :is-disabled="isDisabled"
          @clicked="
            winFunction({
              Points: 3,
              Player: playerIndex,
              Reason: `${playerName} Xtreme Finish`,
            })
          "
        />
        <WinButton
          win-name="Launch Error"
          :is-disabled="isDisabled"
          @clicked="
            winFunction({
              Points: 1,
              Player: playerIndex,
              Reason: `${playerName} Opponent Launch Error`,
            })
          "
        />
      </div>
      <h4 v-if="playerIndex === 0" class="text-7xl grow m-24">
        {{ playerScore }}
      </h4>
    </div>
  </div>
</template>
